default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: jackswarning_development

test:
  <<: *default
  database: jackswarning_test

production:
  <<: *default
  database: jackswarning_production
  username: 
  password: