# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71b06fe4d169b11b52dd6a7a136333718110dad14279bc5e1b745ff77bb14b9ccdf86785430452b42e15db918527a77cefb49d61da5e28ec318cbc8056588cba

test:
  secret_key_base: b67b7c1a576c61963398f77edaa47528fd11f9309e9a923c1fc6212c47aff4b6241f5c6e1a7d9dbb1c5560f43fac1531aefc5cd2b649ecddc36afe091d1de0ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
